#!/usr/bin/env groovy
pipeline {
  agent { label 'docker' }

  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '5'))
    ansiColor('xterm')
    disableConcurrentBuilds()
    timestamps()
    lock resource: 'wlcg-jwt-compliance-lock'
  }

  triggers { cron('00 15 * * *') }

  parameters {
    string(defaultValue: "--exclude strict", description: 'Robot arguments', name: 'ROBOT_ARGS')
  }

  environment {
    OIDC_AGENT_SECRET = credentials('wlcg_jwt_oidc_agent_secret')
    REPORTS_DIR_BASE = '/tmp/reports'
    ROBOT_ARGS = "${params.ROBOT_ARGS}"
    SKIP_REPORT_UPLOAD = 'y'
    MAIL_RECIPIENTS = 'wlcg-doma-tpc@cern.ch'
  }

  stages {
    stage ('run'){
      steps {
        script {
          sh returnStatus: true, script: '''#!/bin/bash 
          set -ex
          mkdir -p reports && rm -rf reports/*
          mkdir -p /tmp/reports  && rm -rf /tmp/reports/*
          mkdir -p ${HOME}/.config/oidc-agent
          cp assets/.config/oidc-agent/* $HOME/.config/oidc-agent/
          docker-compose up trust
          docker-compose up -d ts
          docker-compose exec -T ts bash -c 'cd test-suite && sh ci/run.sh'
          '''
        }
      }
    }

    stage('report'){
      steps {
        sh "docker cp wlcg-jwt-tests_ts_1:/tmp/reports ."
        archive 'reports/**'
      }
    }

    stage('send email'){
      when {
        allOf {
          triggeredBy "TimerTrigger"
          branch "master"
        }
      }
      steps {
        script {
          emailext to: "${env.MAIL_RECIPIENTS}",
          subject: "WLCG JWT compliance test report - #${env.BUILD_NUMBER} ${env.BUILD_TIMESTAMP}",
          body: \
"Report at ${env.BUILD_URL}artifact/reports/reports/latest/joint-report.html\n\n\
Git repository at https://github.com/indigo-iam/wlcg-jwt-compliance-tests"
        }
      }
    }
  }

  post {
    cleanup {
      sh '''#!/bin/bash
      docker-compose down -v
      rm -rf $HOME/.config/oidc-agent
      '''
    }

    failure {
      slackSend color: 'danger', message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Failure (<${env.BUILD_URL}|Open>)"
    }

    changed {
      script{
        if('SUCCESS'.equals(currentBuild.currentResult)) {
          slackSend color: 'good', message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Back to normal (<${env.BUILD_URL}|Open>)"
        }
      }
    }
  }
}
