#!/usr/bin/env groovy
pipeline {
  agent { label 'docker' }

  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '5'))
    ansiColor('xterm')
    disableConcurrentBuilds()
    timestamps()
    lock resource: 'wlcg-jwt-compliance-lock'
  }

  triggers { cron('0 10 * * *') }

  parameters {
    string(defaultValue: 'federica.agostini89@gmail.com', description: 'Job report\'s mail recipients', name: 'MAIL_RECIPIENTS')
  }

  environment {
    OIDC_AGENT_SECRET = credentials('wlcg_jwt_oidc_agent_secret')
    REPORTS_DIR_BASE = '/tmp/reports'
    SKIP_REPORT_UPLOAD = 'y'
    MAIL_RECIPIENTS = "${params.MAIL_RECIPIENTS}"
  }

  stages {
    stage ('run'){
      steps {
        script {
          sh returnStatus: true, script: '''#!/bin/bash 
          set -ex
          mkdir -p reports && rm -rf reports/*
          mkdir -p /tmp/reports  && rm -rf /tmp/reports/*
          docker-compose up trust
          docker-compose up -d ts
          docker-compose exec -T ts bash -c 'cd test-suite && sh ci/run.sh'
          '''
        }
      }
    }

    stage('report'){
      steps {
        sh "docker cp wlcg-jwt-tests_ts_1:/tmp/reports ."
        archive 'reports/**'
      }
    }

    stage('send email'){
      when {
        triggeredBy "TimerTrigger"    
      }
      steps {
        script {
          emailext to: "${env.MAIL_RECIPIENTS}",
          subject: "[Jenkins] ${env.JOB_NAME} report ${env.BUILD_TIMESTAMP}",
          mimeType: 'text/html',
          body: '${FILE,path="reports/reports/latest/joint-report.html"}'
        }
      }
    }
  }

  post {
    cleanup {
      sh '''#!/bin/bash
      docker-compose down -v
      '''
    }

    failure {
      slackSend color: 'danger', message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Failure (<${env.BUILD_URL}|Open>)"
    }

    changed {
      script{
        if('SUCCESS'.equals(currentBuild.currentResult)) {
          slackSend color: 'good', message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Back to normal (<${env.BUILD_URL}|Open>)"
        }
      }
    }
  }
}
